#apiVersion: v1
#kind: Secret
#metadata:
#  namespace: load-gen
#  name: secret
#data:
#  TARGET_HOST: aHR0cDovL2xiLXBlcmYtbG9jdXN0LXdlYi0wZTJiYTI1N2NmYzJmYjBmLmVsYi5hcC1ub3J0aGVhc3QtMi5hbWF6b25hd3MuY29tL2FyZ29jZC9wZXJmLWFkbWluCg==
#  LOCUST_MASTER: bG9jdXN0LW1hc3Rlcgo=
#  MASTER_LOCUST_MODE: bWFzdGVyCg==
#  WORKER_LOCUST_MODE: d29ya2VyCg==
