apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.Common.MasterWebDashBoardName }}
  namespace: {{ .Values.Common.NameSpace }}
  labels:
    app: {{ .Values.Common.MasterGeneratorName }}
spec:
  ports:
    - name: {{ .Values.Common.WebDashBoardPod }}
      port: 8089
      protocol: TCP
      targetPort: 8089
    - name: {{ .Values.Common.MasterPod1 }}
      port: 5557
      protocol: TCP
      targetPort: 5557
    - name: {{ .Values.Common.MasterPod2 }}
      port: 5558
      protocol: TCP
      targetPort: 5558
  selector:
    app.kubernetes.io/name: {{ .Values.Common.MasterGeneratorName }}
  type: ClusterIP
