#apiVersion: v1
#kind: Service
#metadata:
#  name: service-{{ .Values.Common.MasterWebAdminName }}
#  namespace: {{ .Values.Common.Namespace }}
#spec:
#  ports:
#    - port: 80
#      targetPort: 8089
#      protocol: TCP
#  type: ClusterIP
#  selector:
#    app.kubernetes.io/name: {{ .Values.Common.MasterWebAdminName }}
#
#---

apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.Common.MasterWebAdminName }}
  namespace: {{ .Values.Common.Namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP
    - port: 80
      targetPort: 5557
      protocol: TCP
    - port: 80
      targetPort: 5558
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.Common.MasterGeneratorName }}
