apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.Common.MasterGeneratorName }}
  namespace: {{ .Values.Common.NameSpace }}
spec:
  ports:
    - port: 80
      targetPort: 5557
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.Common.MasterGeneratorName }}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.Common.MasterWebAdminName }}
  namespace: {{ .Values.Common.NameSpace }}
spec:
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.Common.MasterGeneratorName }}
  type: ClusterIP
