apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.Common.MasterGeneratorName }}
  namespace: {{ .Values.Common.Namespace }}
spec:
  ports:
    - port: 5557
      targetPort: {{ .Values.Common.MasterPod1 }}
      protocol: TCP
      name: {{ .Values.Common.MasterPod1 }}
    - port: 5558
      targetPort: {{ .Values.Common.MasterPod2 }}
      protocol: TCP
      name: {{ .Values.Common.MasterPod2 }}
  selector:
    app.kubernetes.io/name: {{ .Values.Common.MasterGeneratorName }}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.Common.MasterWebAdminName }}
  namespace: {{ .Values.Common.Namespace }}
spec:
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP
      name: service-{{ .Values.Common.MasterWebAdminName }}
  selector:
    app.kubernetes.io/name: service-{{ .Values.Common.MasterGeneratorName }}
  type: LoadBalancer
